[package]
name = "rift_verifier"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.4"
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v1.0.1" }

[[target.starknet-contract]]
sierra = true
casm = true